"""your migration message2

Revision ID: 8b88eb13d514
Revises: 
Create Date: 2023-08-30 01:48:36.389553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b88eb13d514'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand',
    sa.Column('id', sa.String(length=38), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('platforms', sa.Text(), nullable=False),
    sa.Column('facebook_urls', sa.Text(), nullable=True),
    sa.Column('facebook_hashtags', sa.Text(), nullable=True),
    sa.Column('facebook_groups', sa.Text(), nullable=True),
    sa.Column('tiktok_urls', sa.Text(), nullable=True),
    sa.Column('tiktok_hashtags', sa.Text(), nullable=True),
    sa.Column('tiktok_keywords', sa.Text(), nullable=True),
    sa.Column('youtube_urls', sa.Text(), nullable=True),
    sa.Column('youtube_hashtags', sa.Text(), nullable=True),
    sa.Column('youtube_searchterms', sa.Text(), nullable=True),
    sa.Column('twitter_profiles', sa.Text(), nullable=True),
    sa.Column('twitter_keywords', sa.Text(), nullable=True),
    sa.Column('twitter_country', sa.String(length=50), nullable=True),
    sa.Column('twitter_start_date', sa.Date(), nullable=True),
    sa.Column('twitter_end_date', sa.Date(), nullable=True),
    sa.Column('twitter_language', sa.String(length=50), nullable=True),
    sa.Column('website_urls', sa.Text(), nullable=True),
    sa.Column('camp_id', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['camp_id'], ['campaign.campaign_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('brand')
    # ### end Alembic commands ###
