"""last

Revision ID: c9313bbb353f
Revises: 8b88eb13d514
Create Date: 2023-08-30 06:28:54.946105

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c9313bbb353f'
down_revision = '8b88eb13d514'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brand', schema=None) as batch_op:
        batch_op.drop_column('platforms')

    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.add_column(sa.Column('platforms', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.drop_column('platforms')

    with op.batch_alter_table('brand', schema=None) as batch_op:
        batch_op.add_column(sa.Column('platforms', mysql.TEXT(), nullable=False))

    # ### end Alembic commands ###
